name: Build and Deploy

on:
    push:
        branches:
            - main

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest

        steps:
            - name: Check out the code
              uses: actions/checkout@v4

            - name: Set up bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Use the env.example file
              run: cp .env.example .env

            - name: Run build
              run: bun run build
            
            - name: Copy index.html to 404.html for routing
              run: cp ./dist/index.html ./dist/404.html

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./dist"

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
